### ISSUE TITLE
running time

### ISSUE THREAD

**Issue by cchenghao** [csdwren/PReNet#23]
Why inference time with RESCAN is less than PRENET,  not as described in the paper.  I use GPU.

**Comment by csdwren** [comment]
I do not know why. I am sure that RESCAN takes more time than PReNet, since RESCAN adopts several GRUs in one stage and its backbone network has more parameters than PReNet. I suggest you checking the stage number and quantative results (less inference time can generate same results as reported in the paper?)

**Comment by cchenghao** [comment]
So how many stage number did you use on rescan？

**Comment by csdwren** [comment]
I adopt the default setting of RESCAN. 4 or 6? I did not remember it
